{% set name = "docstring-inheritance" %}
{% set version = "2.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/docstring-inheritance-{{ version }}.tar.gz
  sha256: 154cd62c5e36509b0f60612b11166ece03174ee9c570f5e736aba5aecd10f2b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.13
  run:
    - python >=3.7,<3.13

test:
  imports:
    - docstring_inheritance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AntoineD/docstring-inheritance
  summary: Avoid writing and maintaining duplicated docstrings.
  dev_url: https://github.com/AntoineD/docstring-inheritance
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - AntoineD
