{% set name = "docstring-inheritance" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/docstring-inheritance-{{ version }}.tar.gz
  sha256: 639a3c5975ec0e71ab8b0a8912c32fa9cc0552d1eca49c47da35c9178e0a889b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.11
  run:
    - python >=3.6,<3.11

test:
  imports:
    - docstring_inheritance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AntoineD/docstring-inheritance
  summary: Avoid writing and maintaining duplicated docstrings.
  dev_url: https://github.com/AntoineD/docstring-inheritance
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - AntoineD
