{% set name = "docstring-inheritance" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/docstring-inheritance-{{ version }}.tar.gz
  sha256: 0ce321ba8d160cb6a6eac08f1305411f5f50cfdf10e91cfeec464143190aaaaf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.12
  run:
    - python >=3.7,<3.12

test:
  imports:
    - docstring_inheritance
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AntoineD/docstring-inheritance
  summary: Avoid writing and maintaining duplicated docstrings.
  dev_url: https://github.com/AntoineD/docstring-inheritance
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - AntoineD
